# Note: Name of file should match name of robot in URDF

# Robot Execution Speed
main_velocity_scaling_factor: 0.6 # during planning
approach_velocity_scaling_factor: 0.5
lift_velocity_scaling_factor: 0.6
retreat_velocity_scaling_factor: 0.6
calibration_velocity_scaling_factor: 0.05

# Sleep timers
wait_before_grasp: 0.1
wait_after_grasp: 0.1

# Semantics
start_pose: manipulator_home
dropoff_pose: goal_bin_pose
right_hand_name: gripper
left_hand_name: gripper_DISABLED
right_arm_name: manipulator
left_arm_name: manipulator_DISABLED
both_arms_name: manipulator_DISABLED

# Calibration
shelf_distance_from_robot: 0.52

# Topics
joint_state_topic: /jacob/joint_states