# Note: Name of file should match name of robot in URDF

# Robot Execution Speed
# main_velocity_scaling_factor: 1.0 # during planning
# approach_velocity_scaling_factor: 0.5
# lift_velocity_scaling_factor: 1.0
# retreat_velocity_scaling_factor: 0.6
# calibration_velocity_scaling_factor: 0.05

# DEBUG Robot Execution Speed
main_velocity_scaling_factor: 0.4 # during planning
approach_velocity_scaling_factor: 0.1
lift_velocity_scaling_factor: 0.1
retreat_velocity_scaling_factor: 0.1
calibration_velocity_scaling_factor: 0.3

# Sleep timers
wait_before_grasp: 0.1
wait_after_grasp: 0.1

# Poses
start_pose: manipulator_home
right_arm_dropoff_pose: goal_bin_pose
left_arm_dropoff_pose: left_goal_bin_pose_DISABLED

# Semantics
dual_arm: 0
right_hand_name: gripper
left_hand_name: gripper_DISABLED
right_arm_name: manipulator
left_arm_name: manipulator_DISABLED
both_arms_name: manipulator_DISABLED

# Calibration
world_to_shelf_transform: [0.52, -0.4365, 0.0, 0.0, 0.0, 0.0]  # IDEAL

# Topics
joint_state_topic: /joint_states

# Goal bin - different for each robot
goal_bin_x: -0.35
goal_bin_y: 0.9365
goal_bin_z: 0.4

# Side limits (walls)
left_wall_y: 0 # 0 means disabled
right_wall_y: 0 # 0 means disabled

# Top limit
ceiling_z: 2.4