# Standard: 
#   - prepend with 'show' if it affects rviz
#   - prepend with 'verbose' if it affects console

apc_manager:
  # Goal bin
  show_goal_bin_markers: true

  # Bounding Box
  verbose_bounding_box: false
  
  # Experience planning
  verbose_experience_database_stats: false

  # Cartesian planning
  verbose_cartesian_planning: false
  show_grasp_filter_collision_if_failed: false

  # Seed state
  show_grasping_seed_state: false

  # Unit testing / simulation
  show_simulated_paths_moving: true

  # Multi-use yes/no - can be used for anything
  generic_bool: false