base_link: 'base'
# =====================================================
gripper:
    end_effector_name: 'gripper'  #ee group name

    #actuated joints in end effector
    joints : ['jaco_joint_finger_1','jaco_joint_finger_2','jaco_joint_finger_3']

    #open position
    pregrasp_posture : [0.697, 0.697, 0.697]
    pregrasp_time_from_start : 4.0

    #close position
    grasp_posture : [0.0, 0.0, 0.0]
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    grasp_pose_to_eef :  [-0.05, 0, 0] # NOTE: use when tip of arm is left_gripper. HACK

    #desired pose from end effector to grasp - [r, p, y]
    grasp_pose_to_eef_rotation : [0, 1.5708, 0] # 1.5707 = PI/2

    # max depth of fingers (distance from finger tip to inner palm)
    finger_to_palm_depth : 0.11