initial_x: 0.255
initial_y: -0.09
initial_z: 0.78
initial_roll: 6.27159
initial_pitch: 0.13
initial_yaw: 1.74
from: gantry_plate
to: xtion_right_link
file_name: tf_xtion_right
topic_name: /keyboard_right/keydown
