initial_x: 0.686
initial_y: -0.417
initial_z: -0.183
initial_roll: 0.015
initial_pitch: -0.014
initial_yaw: -0.016
from: world
to: shelf
file_name: tf_keyboard_world_to_shelf
topic_name: /keyboard_world_to_shelf/keydown
