initial_x: 0.2
initial_y: -1.57
initial_z: 0
initial_roll: -1.57
initial_pitch: 1.57
initial_yaw: 0
from: calibration_target_frame
to: shelf
file_name: tf_keyboard_shelf_offset
topic_name: /keyboard_shelf_offset/keydown
