initial_x: 0.265
initial_y: -0.081
initial_z: 0.696
initial_roll: 6.21859
initial_pitch: 0.14
initial_yaw: 1.742
from: gantry_plate
to: xtion_right_link
file_name: tf_xtion_right
topic_name: /keyboard_xtion_right/keydown
