initial_x: 0.26
initial_y: -0.042
initial_z: 0.712
initial_roll: 6.22459
initial_pitch: 0.154
initial_yaw: 1.742
from: gantry_plate
to: xtion_right_link
file_name: tf_xtion_right
topic_name: /keyboard_xtion_right/keydown
