initial_x: -0.448
initial_y: -0.016
initial_z: 0.711
initial_roll: -0.00159
initial_pitch: 0.3
initial_yaw: 1.348
from: gantry_plate
to: xtion_left_link
file_name: tf_xtion_left
topic_name: /keyboard_left/keydown
