initial_x: -0.44
initial_y: 0.021
initial_z: 0.711
initial_roll: 0.00241
initial_pitch: 0.286
initial_yaw: 1.35
from: gantry_plate
to: xtion_left_link
file_name: tf_xtion_left
topic_name: /keyboard_xtion_left/keydown
