initial_x: -0.453
initial_y: 0.021
initial_z: 0.718
initial_roll: -0.03259
initial_pitch: 0.169
initial_yaw: 1.171
from: gantry_plate
to: xtion_left_link
file_name: tf_xtion_left
topic_name: /keyboard_xtion_left/keydown
