initial_x: 0.25
initial_y: -0.064
initial_z: 0.709
initial_roll: 6.22659
initial_pitch: 0.145
initial_yaw: 1.861
from: gantry_plate
to: xtion_right_link
file_name: tf_xtion_right
topic_name: /keyboard_xtion_right/keydown
