initial_x: 0.27
initial_y: -0.077
initial_z: 0.704
initial_roll: 6.22859
initial_pitch: -0.01
initial_yaw: 1.762
from: gantry_plate
to: xtion_right_link
file_name: tf_xtion_right
topic_name: /keyboard_xtion_right/keydown
